### PR TITLE
Add uniform_filter/1d

### PR DESCRIPTION
**Pull request by matsjoyce-refeyn**
Add a uniform filter implementation in the same style as the existing gaussian filter. It's not going to be as quite as fast as scipy, because scipy's implementation hardcodes the fact that the weights are constant, but I really don't want to duplicate the border modes implementation.

Also fixed a few typos. Tests run with rustc 1.72.0 and ndarray 0.15.6.

### CODE REVIEW

**Comment by nilgoyette** [comment]
> Currently hardcoded with the `PadMode::Reflect` padding mode.

It's weird, I don't even remember why I wrote that comment. I don't see any padding in that code... I guess it was padding OR border management.

Anyway, thank you for the contribution! You're my first contributor :confetti_ball: I probably will merge this as is.

Can you please give more details about

> It's not going to be as quite as fast as scipy, because scipy's implementation hardcodes the fact that the weights are constant, but I really don't want to duplicate the border modes implementation.

It will help me later if/when I want to code it.

**Comment by matsjoyce-refeyn** [comment]
> > Currently hardcoded with the `PadMode::Reflect` padding mode.
> 
> It's weird, I don't even remember why I wrote that comment. I don't see any padding in that code... I guess it was padding OR border management.

Yes, I couldn't quite work it out either, so I left it as is (Chesterton's Fence and all that).

> Can you please give more details about
> 
> > It's not going to be as quite as fast as scipy, because scipy's implementation hardcodes the fact that the weights are constant, but I really don't want to duplicate the border modes implementation.
> 
> It will help me later if/when I want to code it.

Based on the code (https://github.com/scipy/scipy/blob/main/scipy/ndimage/src/ni_filters.c#L359-L362), scipy is using a single accumulator as it moves along lines, and just adds the new value and subtracts the oldest value each time the filter moves to a new sample. Then it just divides by the filter size, which should be a lot more efficient than a correlation. Looking again at the `inner_collerate1d` code, it should be possible to do something similar here, but it probably makes sense to do that in a subsequent PR for simplicity. I might have a go at that, it's made me curious now 😁.

> Anyway, thank you for the contribution! You're my first contributor 🎊 I probably will merge this as is.

No problem! This package has been very useful for me, I'm converting some numpy/scipy code into Rust and it's surprisingly difficult to find packages implementing things like blurs and labelling for data that is not standard 2D RGB images. And as a bonus, this package uses ndarray so I don't need any conversion code from nalgebra or similar either!

**Comment by nilgoyette** [comment]
Thank you! I created this [issue](https://github.com/imeka/ndarray-ndimage/issues/21) for later.

Do you require a release with this feature?

**Comment by matsjoyce-refeyn** [comment]
> Do you require a release with this feature?

We will at some point (in the next month or so), but if you have a release planned already I can just wait for that.

**Pull request merged**
